### PR TITLE
fix #290 use pythondir var as base for setting PYTHONLIBDIR

### LINKED ISSUE #290: [BUG] fix Python 3 default install dir so special PYTHONPATH is not needed
**Describe the bug**
When building from source, you can no longer use 'sudo core-daemon', and have to prepend the command with the appropriate "PYTHONPATH=" setting.

**To Reproduce**
Under Ubuntu 18.04, using `PYTHON=python3 ./configure`, CORE is installed to `/usr/local/lib/python3/dist-packages`, whereas `/usr/local/lib/python3.6/dist-packages` is in the default path.

**Expected behavior**
We should be able to ./bootstrap.sh && configure && make && sudo make install with the minimum number of variables and switches. Default config should be as easy as possible.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - CORE Version 5.4.0
 - EMANE Version N/A

**Additional context**
Pull request to address this is coming...

### PR DESCRIPTION
**Pull request by siliconja**
This causes PYTHONLIBDIR to be set to `/usr/local/lib/python3.6/dist-packages` under Ubuntu 18.04 when configured with `PYTHON=python3 ./configure`, which is in the default Python 3 search path.

Note that `/usr/lib/python3/dist-packages` is in this default path (so it works if you're configuring with `--prefix=/usr`), but the `/usr/local` path has `/usr/local/lib/python3.6/dist-packages`.

### CODE REVIEW

**Comment by bharnden** [comment]
I'll move some thoughts here specifically.

* need to account for ns3 python code in the same way
* $(subst site-packages,dist-packages,$(pythondir)) seems to be a simpler built in way for substitution
* /usr/lib/python3 was assumed to exist usually, otherwise building package (RPMs etc) would lock to a specific version of python3, in your case it doesn't but that's bad news then I guess =(

**Comment by siliconja** [comment]
OK this seems to work for me!

**Comment by bharnden** [comment]
Added a configure option for python3, which is better than having to have PYTHON-python3, in case that is not something within your path. It is only used for building packages currently. I'll have to see what is best to do about the whole python version used and paths for building packages still.

**Comment by siliconja** [comment]
What would be nice is for ./configure to look for Python 3 and Python 2, and just use Python 3 if it is present. i.e. no extra flags, and definitely no extra environment variables.

**Comment by bharnden** [comment]
Good idea, may help in transitioning to python3 at some level anyway. My hope is to likely drop python2 in the near future anyway.

**Comment by bharnden** [comment]
Played around a bit and nothing to allow it working in that way easily, at least that I could find. I'll merge this for now. This gets resolved at some level when we just drop python2 =).

**Pull request merged**
