### PR TITLE
Merged pull requests

### PR DESCRIPTION
**Pull request by MaralAfris**
Hi !

I did a major merge of the pending pull requests on the project (requests #71 , #74, #97, #98 and #112).
Tested on ubuntu, runs fine for me.

Hope you have some time to review and merge :) And mostly that I gained you time by doing this ;)

All the best !

### CODE REVIEW

**Comment by Shatnerz** [comment]
Nice work @MaralAfris. Hopefully this gets though eventually

**Comment by siliconja** [comment]
Wow this is a lot of changes in one.

- Did you try out CORE with docker and is it again working? Which Linux did you test with?
- With all of the import changes, do you know if the sample Python scripts are still working?
- For the link buffer size changes, my question to the author in that PR is whether this is supported with the save/load to/from the imn scenario file? (Can you save the buffer size and save that?)

**Comment by siliconja** [comment]
Wondering if you had a chance to look at my questions above?

I'm thinking it may be better to deal with each pull request individually. Simplify code review, etc.

**Comment by MaralAfris** [comment]
Hi,

Sorry I was away... So here are the answers.
- Haven't tried with docker yet, it is on my todo list actually :) It tested it on ubuntu 17.04
- Ahah haven't tried those actually, I should
- That's a good one.

Sure, it is a huge chunk of code. My idea was to integrate those and run on my computer and see how it goes (I will run docker containers so they seemed interesting for me). Feel free to integrate each individually. The only one really taking time are the buffer and the cleaning because most of the changes are at the same spots, they are trivial but still you need to fix them by hand...)

But feel free to integrate on your side, I will just follow master and contribute on the way in a smaller way then ;)

**Pull request closed without merging**
