### PR TITLE
make python-sphinx optional

### PR DESCRIPTION
**Pull request by siliconja**
This turns off docs build if the python-sphinx package is missing, instead of bombing out with an error.

- make python-sphinx optional

### CODE REVIEW

**Comment by bharnden** [comment]
This can be OK, I was thinking docs are set to on by default and that this check should have been hidden behind that flag and only checked when docs are really wanted. If I recall correctly.

**Comment by siliconja** [comment]
Yes, the docs are on by default, and simply running './configure' will fail, unless you have python-sphinx installed. Under Ubuntu 18.04, this involves installing 29 new packages / 41 MB.  With this change, you do not need the python-sphinx package installed, and ./configure will WARN instead of ERROR for the missing packages, and will not try to build the docs.

Consider a headless CORE emulation server, where you want to run CORE but not develop there. You want to simply run './configure && make && sudo make install' and don't care for building any documentation.

**Comment by bharnden** [comment]
I agree, I was more or less saying that I felt making docs off by default might be the better way to go about it. At least that's what I was thinking when I noticed this case.

**Comment by bharnden** [comment]
This looks good, thanks. It shouldn't as the docs are all in markdown and served by GitHub, beyond the python documentation that still would get generated by sphinx. But, that is not a part of FPM.

**Pull request merged**
