### PR TITLE
Docker Work in Progress

### PR DESCRIPTION
**Pull request by stuartmarsden**
I contributed the docker service some years ago. It was always a hack and is fairly broken now. I wanted to do this in the right way.

This pull request removes the old docker service and tries to make a docker network node. This is an extension of the LxBrNet but gets docker to create a bridge network and then works out the bridge name. From then on it works as a standard bridge network. You can then run docker containers in this network and they will be on the same subnet as any connected core nodes and can see each other. The docker.py example file shows how this can work.

Limitations:
- Figuring out the docker network bridge name is still slightly hackish as it is not exposed by the API
- While a CORE switch obviously does not need an IP the Docker one does as it will use the subnet and gateway to assign container IPs
- No method for preventing IP clashes between containers and CORE nodes.

TODO:

- Add to the GUI. I do not use the GUI much and am happy to have it just via the python API. I do not know Tcl/Tk so would need help to add it.
- Add to the message API. I am not sure how to properly do that. I added it to enumerations.py but assume the message would have to be defined to take the new params (subnet, gateway). Help appreciated.
- Add a Docker container node. As a convenience I could add a node that runs a docker container and attaches it to a docker net. Again this is most useful for the GUI as the same can be done with standard Docker.

This is probably not ready for 5.1 which seems imminent (though it only extends so could be in just for early testing). I am looking for feedback to improve and this pull request will update as I update my docker branch. 

Some diagrams to explain courtesy of @gsomlo 

The old way used to have a full docker server run in each node and needed lots of hacks:

       -------------
       | Host (L0) |
       ------+------
             |
             +------------------------+
             |                        |
    ---------+----------     ---------+----------
    | Core Node A (L1) | ... | Core Node B (L1) |
    --------------------     ----------+---------
                                       |
                           +-----------+-------------+
                           |                         |
                -----------+---------     -----------+---------
                | Docker Img 1 (L2) | ... | Docker Img 2 (L2) |
                ---------------------     ---------------------

The new way builds CORE nodes and Docker containers at the host level and the wires them together with bridges.

          -------------
          | Host (L0) |
          ---+-----+---
             |     |
             |     +-------------------------------+----------------+
             +-----------------+                   |                |
             |                 |                   |                |
    ---------+-----     -------+-------       -----+------     -----+------
    | Core Node A | ... | Core Node B |       | Docker 1 | ... | Docker 2 |
    ---------+-----     -------+-------       -----+------     -----+------
                               |                   |
                               +-------------------+
                               "docker bridge"

### CODE REVIEW

**Comment by stuartmarsden** [comment]
Another limitation is that it does not seem to work Node->Switch->Docker Network->Container

It sets ups the veth between the CORE Switch bridge and the docker network bridge but nothing goes across. Probably some forwarding rules but I cannot figure it out at the moment.

**Comment by siliconja** [comment]
I was also just experimenting with a veth pair to join the docker0 bridge with the a CORE-based bridge. Ran into the same issue. An easy workaround for me was to link a switch to a router (using CORE GUI). 

- On the (CORE-based) router, configure the interface going to the switch something like 172.16.0.2/24
- on the host, assign an IP to the switch node, such as 172.16.0.1/24
- at the router, add a static route to 172.17.0.0/16 to route traffic to the docker IPs ( ip ro add 172.17.0.0/16 via 172.16.0.1)
- now ping may not work, but if you forward specific ports using e.g. "docker run -p 8080:8080", those are accessible

**Comment by stuartmarsden** [comment]
I should probably add a special mode to connect to the docker0 bridge. Maybe just check if the node has been called docker0 and then don't create a new network but use the existing bridge.

The limitation with using docker0 is that you connect to the whole docker instance and so this does not let you do network effects between docker containers. The docker network approach allows this so that is the way I went.

Any tips on how to add this to the messaging API and maybe the GUI?

**Comment by D3f0** [comment]
Using ubridge or pipework would be an overkill for connecting Docker to the CORE container?

**Comment by stuartmarsden** [comment]
Not sure ubridge or pipeworks brings anything that can't be done with the standard docker network drivers.

**Comment by stuartmarsden** [comment]
I figured out that I can make the docker networks internal and this stops an issue that it would clash with the same network subnet on a completely unrelated CORE emulation.

This now also means that  I can connect a docker bridge to a CORE bridge and have it work as expected.

**Comment by gsomlo** [comment]
I am using stock Fedora (28), with distro-packaged docker (1.13.1-56.git6c336e4, FWIW). With (or without) these patches, I can only run docker images from within a CORE node after (re)mounting the /sys/fs/cgroup tree (also, https://publists.nrl.navy.mil/pipermail/core-users/2018-April/002308.html). The startup script I have to use looks like this:
```
        #!/bin/sh
        #
        # Mount /sys/fs/cgroup hierarchy based on the info in /proc/mounts:
        mount -T /proc/mounts -o rw /sys/fs/cgroup
        for MP in $(grep ^cgroup /proc/mounts | cut -d' ' -f2 | sort -u); do
          [ -d $MP ] || mkdir -p $MP
          mount -T /proc/mounts $MP
        done
        # Symlink individual entries for comma-separated "pairs":
        for DD in $(ls /sys/fs/cgroup | grep ,); do
          for D in ${DD/,/ }; do
            ln -s $DD /sys/fs/cgroup/$D
          done
        done
        # Remount /sys/fs/cgroup read-only for long-term use:
        mount -o remount,ro /sys/fs/cgroup
        #
        # Note: to clean up, use "umount /sys/fs/cgroup/* /sys/fs/cgroup"
        # 
        #
        # Start docker-containerd:
        /usr/libexec/docker/docker-containerd-current \
          --listen unix:///run/containerd.sock \
          --shim /usr/libexec/docker/docker-containerd-shim-current \
          2>/var/log/containerd.log &
        #
        # Start dockerd:
        /usr/bin/dockerd-current \
          --add-runtime oci=/usr/libexec/docker/docker-runc-current \
          --default-runtime=oci \
          --containerd /run/containerd.sock \
          --userland-proxy-path=/usr/libexec/docker/docker-proxy-current \
          --init-path=/usr/libexec/docker/docker-init-current \
          --seccomp-profile=/etc/docker/seccomp.json \
          -g /var/lib/docker \
          2>/var/log/dockerd.log &
        #
        # At this point, we may run the docker client:
        # docker info
        # docker image ls
        # docker run hello-world
        #
        #
        # For reference, the original docker startup script from CORE:
        #
        # auto-generated by Docker (docker.py)
        #echo "nameserver 8.8.8.8" > /run/resolvconf/resolv.conf
        #/usr/bin/docker-current daemon
        # you could add a command to start a image here eg:
        # docker run -d --net host --name coreDock <imagename>
```
I'm not sure how (with these patches applied) to set up a CORE node as a "docker node" (or enable a Docker service on a different node type), but I imagine that in order to run dockerfiles nested within CORE containers we'd have to deal with /sys/fs/cgroup, whether on Fedora or Ubuntu or any other distro.
If I'm missing something obvious, please accept my apologies, and please advise on how I could test these patches :)

Thx,
--G

**Comment by stuartmarsden** [comment]
@gsomlo As I said on the mailing list. The old way was very broken and I don't recommend it. The new way is a work in progress but is a much neater solution. It is not exposed in the GUI so the only way to try is using the python API. An example is at examples/api/docker.py

**Comment by kplax** [comment]
Have there been an updates to this?  Has anyone attempted to run docker inside an LXC?  I have seen cgroup errors in the past and was wondering if anyone experienced anything similar.  

No logs available yet.

**Comment by gsomlo** [comment]
@kplax: at the time I wrote [this comment](https://github.com/coreemu/core/pull/165#issuecomment-393631104), you could run dockers nested inside an LXC/CORE container after following the instructions on how to re-mount /proc/mounts from within the container.

However, as further comments state, that's a poor way of integrating dockers and CORE. The better solution would be to run CORE/LXC and Docker side by side, and have CORE provide a network bridge to DOCKER on which the latter can connect and start new containers (see [here](https://github.com/coreemu/core/pull/165#issuecomment-393758252)).

The latter, "correct" solution also depends on Docker abstaining from forcibly adding an IP address to bridge interfaces for the layer-3 default gateway. That work has been stuck in review for quite a while, without any outright rejection or negative feedback: see https://github.com/moby/moby/pull/37432 and https://github.com/docker/libnetwork/pull/2317 for the details.

**Comment by kplax** [comment]
Would each docker instance/core node need to have its own bridge? See below:

      -------------
      | Host (L0) |
      ---+-----+---
         |     |
         |     +-------------------------------+----------------+
         +-----------------+                   |                |
         |                 |                   |                |
    ---------+-----     -------+-------       -----+------     -----+------
    | Core Node A |     |   Docker 1  |       | CoreNodeN|     | Docker N |
    ---------+-----     -------+-------       -----+------     -----+------
         |                 |                   |                |
         +-----------------+                   +----------------+
           "docker bridge1"                     "docker bridge N"

**Comment by stuartmarsden** [comment]
I kind of ran out of time to look at this as life got complicated.

It did not seem to get much traction from the devs and without a prospect of getting it upstream I kind of lost interest.

Essentially CORE and Docker do the same thing. Create containers, make a veth pair and place one half inside. It then uses bridges to tie it all together.

If you actually go to the shell it is quite trivial to bring them all together using the standard Linux IP tools.

There are a few gotchas though:

- As @gsomlo noted above Docker wants to assign an IP to the bridge which does not sit will with CORE. @gsomlo has tried to get an option to stop this behaviour but it is not been pulled yet
- The biggest issue though is that Docker hides its inner working so finding the veth pair name for a container is difficult. They do this for a reason as they may change the underlying mechanism and retain the same API (for instance overlay networks for swarms) but it means some sort of hacks to determine the right veth in the host.

What docker does have is a plugin system and you could add your own network implementation. This could then use the CORE logic to build both networks. A docker container would just be a different CORE node.

I think that is the best route. I looked at the API for making plugins and it is quite straightforward I just have not had the time to attempt it. Perhaps someone else could give it a go.

**Comment by gsomlo** [comment]
No reason why you couldn't have multiple docker instances on the same
bridge, e.g.:

   -------------
   | Host (L0) |
   ---+-----+---
    C |     | D
      |     +-----------+-----------------------+
      +                 |                       |
      |                 |                       |
 ---------+-----     -------+-------       -----+------
 | Core Node A |     |   Docker 1  |  ...  | Docker N |
 ------+--------     -------+-------       -----+------
       |                    |                   |
       +--------------------+-------------------+
        "docker bridge1"

It all depends on how the future docker integration support is written 
in CORE -- it is CORE who will issue "docker network create <foo>" and
"docker container start -network <foo> -image <bar>" commands
(paraphrasing the docker command syntax, don't hold me to it :) ).

Once a network (bridge) is created, multiple docker instances can be
connected to it, just like if you issued the commands manually.

The problem with Docker right now is that it absolutely wants to add
the subnet default gateway IP to the bridge interface, which is
something we'd like to avoid (hence the moby and libnetwork pull
requests).

**Comment by siliconja** [comment]
In the latest CORE you can link a router to a switch, and name the switch "**docker0**". Then instead of creating a new Linux bridge (to link the connected nodes), CORE will link the host-side veth interfaces to the existing docker0 bridge.

If you give that router/node/etc. an address on that docker subnet (172.17.x.x/16) then you can easily communicate with docker nodes from the CORE nodes.

core-linked-with-docker

**Comment by bharnden** [comment]
When I had time a long time ago to play with the docker containers a bit, you could set the network to none by default and then link them with veth pairs.

```shell
docker run -td --net=none --name container1 hsflowd /bin/bash
```

Does this still persist the bridging issue noted above?

**Comment by stuartmarsden** [comment]
> In the latest CORE you can link a router to a switch, and name the switch "**docker0**". Then instead of creating a new Linux bridge (to link the connected nodes), CORE will link the host-side veth interfaces to the existing docker0 bridge.

Interesting is that specific to just docker0? I think in most use cases you would want to apply a network topology and effects between different Docker containers. If you could create a docker bridge network and then name the switch the same then you could build that up quite easily. I still think that you would run in to trouble with default gateways on the docker bridge or have you mitigated that somehow.

**Comment by siliconja** [comment]
> Interesting is that specific to just docker0?

You can do this with any Linux bridge present on the host.  If the provided name matches an existing bridge name ("docker0", "docker1", "mybridge", etc.), then we join the bridge instead of auto-generating a new one.

**Comment by stuartmarsden** [comment]
> Does this still persist the bridging issue noted above?

In theory that would be a sound approach and essentially puts all of the work of creating the network on you.

If I remember right Docker hides its network name spaces so you cant just do:

`ip link set veth1 netns dockercontainernamespace`

I think there is a hack where you symlink to where docker keeps its namespaces.

The down side of this for me is that you cannot use the Docker networks to deploy it in the same way you would in production and have to replicate the topology using CORE.

**Comment by stuartmarsden** [comment]
> You can do this with any Linux bridge present on the host. If the provided name matches an existing bridge name ("docker0", "docker1", "mybridge", etc.), then we join the bridge instead of auto-generating a new one.

This should be a good interim solution you create as many different network sections as you want by creating docker bridge networks:

`docker network create -o "com.docker.network.bridge.name"="mybridge" mybridge`

Note the option to specify what the bridge name will be so you know it.

Then you just add a switch in CORE of the same name. You will have to manually set the Docker and CORE IP scheme to match. I think I tried this before but the bridge gateway IP that docker set confused me and I gave up.

**Comment by stuartmarsden** [comment]
> I think I tried this before but the bridge gateway IP that docker set confused me and I gave up.

Further to this maybe it is as simple as doing something like 

`ip addr del 172.21.0.1/16 dev mybridge`

Docker should then still set the gateway for new containers attached to the network but the bridge will no longer be the gateway and you can set a router using CORE as the gateway IP. 

I don't actually have CORE and Docker installed together on anything at the moment so cannot confirm this but see no reason it would not work. 

So probably the simplest thing would to be have CORE have a specialisation of the switch node. This has almost all the same logic but instead of creating the bridge it creates a docker network. It then removes any ip assigned to that bridge. Everything else would work the same.

**Comment by kplax** [comment]
> In the latest CORE you can link a router to a switch, and name the switch "**docker0**". Then instead of creating a new Linux bridge (to link the connected nodes), CORE will link the host-side veth interfaces to the existing docker0 bridge.
> 
> If you give that router/node/etc. an address on that docker subnet (172.17.x.x/16) then you can easily communicate with docker nodes from the CORE nodes.
> 
> core-linked-with-docker

So I have CORE 5.2.1 and this method did not work for me.  When I name my switch/hub (tried both) to the name of the existing docker bridge, it does not add the host side veth to the existing bridge - it creates a new bridge.  Now from the host side I can shut off then delete the new bridge, then add the veth to the docker bridge and all is well - but this method is not efficient.  I'm not sure how CORE chooses the names for veth and the switch bridge, so it seems difficult to script the shutdown switch bridge, delete switch bridge, and add to veth to docker bridge.

Any idea why CORE is not behaving the way you explained it?

**Comment by siliconja** [comment]
> Any idea why CORE is not behaving the way you explained it?

Sorry, it appears the PR for this has not been merged: https://github.com/coreemu/core/pull/220

(I thought it was in the latest code, b/c I'm running off my branch...)

I would look at the commit and try patching your copy...

**Comment by Kevlar** [comment]
Hi everyone.  I'll take responsibility for dragging our feet on this.  I've been having discussions about supplementing the CORE namespaces (often referred to as LXCs) with Docker as a second native container in CORE.  That thread got derailed and I never was able to circle back to this.  
I'm mostly familiar with docker conceptually, but would love to flush this out with ideas on how we might implement it.  
I'd love to have some discussion on how we might implement something and would invite anyone interested into the docker channel on discord.

**Comment by bharnden** [comment]
There are thoughts of looking into adding a bridge integration node, to allow bringing in something like Docker. There is also the new GUIs integrations with Docker and LXC nodes, that could potentially fulfill the same purpose.

The new functionality for Docker is considered reasonable enough, feel free to let us know what is missing. Closing this for now.

**Pull request closed without merging**
