### PR TITLE
allow passing in a Session class to CoreEmu.create_session() helper

### PR DESCRIPTION
**Pull request by siliconja**
This allows for a Python script that subclasses the EmuSession object.

For example:
```python
class HipSession(EmuSession):
    ''' ...insert custom code here
    '''

# use the create_session() helper with our custom class
session = coreemu.create_session(_cls=HipSession)
# now we can easily connect the GUI to our Session
```

- allow passing in a Session class to CoreEmu.create_session() helper

  Signed-off-by: Jeff Ahrenholz <siliconja@users.noreply.github.com>

### CODE REVIEW

**Comment by bharnden** [comment]
So that you can execute the script from the UI? What logic would you be adding to a session that might not be globally useful?

Otherwise injecting the session directly would work the same.

```python
coreemu.sessions[hip_session.session_id] = hip_session
```

**Comment by siliconja** [comment]
The pythonic way to create an "experiment" script is to subclass a EmuSession, and the pythonic way to extend a node is subclassing a CoreNode. One could duplicate the contents of CoreEmu.create_session(), however subclassing keeps the code DRY, and protects the script writer from future changes to the create_session() helper. (i.e. reduced script maintenance.)

There are various bits of logic that could be considered "experiment-specific" that would be added to the new session class in such a script; these items would not make sense globally. Plus, assume the script writer prefers to maintain their own code/test scripts, and not track a private fork of CORE, if possible.

**Comment by bharnden** [comment]
I understand that. I guess I was more curious why you really needed to do it? This is the first I have heard/seen of anyone trying to subclass a Session.

**Comment by siliconja** [comment]
Here is a public example (working on a similar version in private repo):

- https://bitbucket.org/openhip/openhip/src/master/src/util/scripts/hiptest.py

CORE is useful to run protocol self-tests! You can build an entire network experiment and run a protocol through different scenarios. Plus, you can optionally attach the GUI (or just a set of shells) when you want to go in and troubleshoot.

I'm migrating from CORE 4.8 to 5.2 so running into all kinds of fun.

**Pull request merged**
