### PR TITLE
[RFC] Support configuring link buffer sizes

### PR DESCRIPTION
**Pull request by tohojo**
This adds support for configuring link buffer sizes in the virtual topology. Buffer size is configured in number of packets, and only active when bandwidth limitations are in effect. If no buffer size is configured, a reasonable default is calculated based on the configured BDP if delay is set, or defaults to 1000 packets otherwise.

This is only implemented for the netns backend. As part of this change, TBF is no longer used for shaping links; it is replaced by netem's 'rate' parameter. The netem shaper is rate based instead of token bucket based, which improves accuracy of the bandwidth shaping. However, the rate feature of netem has only been present since Linux v3.3, while TBF is significantly older.

We have been running this code in our lab for a while (on top of v4.8 of Core), and it has been used by students in a TCP performance modelling course. This pull request is a straight-forward rebase onto the current master branch and is mostly meant as an RFC to get some feedback on whether there is interest in merging something like this. I am fine with spending some time making any needed adjustments if there is; though I'm not sure how to add the same capabilities to the other backends...

### CODE REVIEW

**Comment by justas-** [comment]
I tested this pull request while investigating the posibility of using NetEm as a replacement for TBF, and it does not work as intended if only bw is set. Specifically the first if on line 388:

```
if delay <= 0 and jitter <= 0 and loss <= 0 and duplicate <= 0:
    # possibly remove netem if it exists and parent queue wasn't removed
    if not netif.getparam('has_netem'):
        return
```

Will eval to true if all params are None. Then the second if will cause function to return without applying the qdisc.

**Comment by tohojo** [comment]
Ah, right, that should probably have added bw to that check. Thanks for testing!

Pushed an updated version that just fixes that if you want to test; but it seems rebasing on master is non-trivial, so I'll have to come back to that...

**Comment by siliconja** [comment]
this PR either should be rebased/fixed for master merge or the merge target could be the rel/4.8 branch (where the old pre-5.x CORE codebase lives)

**Comment by tohojo** [comment]
Ah, didn't realise there was a separate branch. Thanks for pointing that out! Changed the base; don't have time to work on forward-porting this for the time being, unfortunately...

**Comment by SamBosch** [comment]
This PR assumes that the MTU is the standard 1500 Bytes. In our lab we found in necessary to account for jumbo frame size in setting the buffer size to get the correct performance.

**Comment by tohojo** [comment]
Well, seeing as this has been sitting around for two years, I don't suppose there's much chance of it getting merged; so not going to do any more work on it. Feel free to take over the code and submit an updated pull request, though...

**Comment by bharnden** [comment]
We can talk this over about potentially adding to the new GUI and seeing what make sense to try in adding in, if this is useful to others.

Also be good to know more for @SamBosch case to potentially account for his issue as well.

**Comment by bharnden** [comment]
Updating to note that thanks for this input and some of the logic was worked in to help correct limits being set when delay is leveraged and to factor in the MTU set on the interface being configured from input provided in this thread.

I will keep this open, since the next step in the future would be to add the options for configuring limit/buffer as the original intent of this pull request offered.

**Comment by bharnden** [comment]
I added the configuration of buffer/limit to code and formal support within the new python GUI. Thanks again for bringing this up and contributing this effort.

**Comment by tohojo** [comment]
bharnden <notifications@github.com> writes:

> I added the configuration of buffer/limit to code and formal support
> within the new python GUI. Thanks again for bringing this up and
> contributing this effort.

Awesome! And you're welcome :)

**Pull request closed without merging**
