### PR TITLE
Bugfix/fix 387 gnome terminal launch

### PR DESCRIPTION
**Pull request by siliconja**
Fix quoting to allow gnome-terminal to launch properly under coretk-gui. Tested also with xterm OK.

### CODE REVIEW

**Comment by siliconja** [comment]
strange about the isort checks failing; when I committed locally (Ubuntu 18.04) it ran the isort check and automatically changed the files `daemon/core/configservice/base.py` and  `daemon/core/location/geo.py` and now those are the files it is complaining about...

**Comment by bharnden** [comment]
I felt like there was something that was complaining about not having quotes. There definitely needs to be some thoughts or additions for handling things like xterm256 and other settings. Potentially using $TERM is not the right answer.

When isort changed things, did you then re-add the changes and commit again? Just checking.

**Comment by siliconja** [comment]
yes my isort made those changes, not me :)

I only intended to change the quoting on that one line in that one file. :)

**Comment by bharnden** [comment]
I was checking is the changes were then re-added for the commit? That is what I was checking on.

Since the checks will make changes, but the changes don't take by default. Just making sure I understood exactly what happened.

Does seem odd though. I will check on these files manually now.

**Comment by bharnden** [comment]
And what version of isort is this to check? I am not seeing these changes being applied manually checking.

**Pull request closed without merging**
